### ISSUE TITLE
Compare to Gorilla Schema

### ISSUE THREAD

**Issue by earthboundkid** [chanced/labeler#1]
Cool project. The README says you only looked at Netflix go-env as prior art, but I think [Gorilla Schema](https://github.com/gorilla/schema) is pretty similar. It may be worth taking the time to pick it over for ideas.

**Comment by chanced** [comment]
Thanks! I wasn't aware of it. This was my first project in Go so the landscape is fairly new to me.

It seems they cache schemas, which is something I need to do as well. I'm fairly certain it won't require much to add it in but I want to make sure it is stable enough before introducing memoization. [Using goroutines and channels to build the schema](https://github.com/chanced/labeler/blob/master/channels.go), while educational and seemingly performant, has me a bit on edge. 

They also have require validation. It was something that I initially built in but removed. After some reflection, validation seemed like scope creep. A library dedicated to validation could likely handle those concerns with more flexibility and precision while providing appropriate contextual feedback. 

Being able to register encoders/decoders is something that I could probably introduce fairly easily. I'm just not sure there's enough interest to warrant it.

For example, this is how I'm handling unmarhsaling `Time` and `Duration` from the `time` package:

```go
var fieldStringeePkgs = map[string]map[string]fieldStringee{
	"time": {
		"Time": func(f *field, s string, o Options) error {
			return f.setTime(s, o)
		},
		"Duration": func(f *field, s string, o Options) error {
			return f.setDuration(s, o)
		},
	},
}
```
which is bootstrapped using:

```go
var unmarshalFieldPkgString unmarshaler = func(r reflected, o Options) unmarshal {
	if r.Topic() != fieldTopic {
		return nil
	}
	set, ok := fieldStringeePkgs[r.PkgPath()][r.TypeName()]
	if !ok {
		return nil
	}
	return set.Unmarshaler(r, o)
}
```
From https://github.com/chanced/labeler/blob/master/unmarshalers.go#L155-L164

**Comment by chanced** [comment]
I should note that while the project doesn't currently have a way to register marshalers/unmarshalers or encoders/decoders, it is still fairly flexible through very concise interfaces.
